(define (problem roverPro22) (:domain roverTo22)
(:objects
L0 L1 L2 L3 L4 L5  - lugar
R0 R1  - rover
P0 P1  - persona
S0  - suministro
)
(:init
(camino L0, L1)
(camino L1, L0)
(camino L1, L2)
(camino L2, L1)
(camino L2, L3)
(camino L3, L2)
(camino L3, L4)
(camino L4, L3)
(camino L4, L5)
(camino L5, L4)
(camino L1, L4)
(camino L4, L1)
(camino L4, L2)
(camino L2, L4)
(camino L5, L3)
(camino L3, L5)
(en R0, L1)
(en R1, L4)
(en P0, L0)
(en P1, L0)
(en S0, L1)
(= (libre R0) 2)
(= (libre R1) 2)
(= (combustible R0) 16)
(= (combustible R1) 38)
(= (combustible_total) 54)
(= (peticion_persona L0) 1)
(= (peticion_persona L1) 2)
(= (peticion_persona L2) 0)
(= (peticion_persona L3) 3)
(= (peticion_persona L4) 3)
(= (peticion_persona L5) 1)
(= (peticion_suministro L0) 2)
(= (peticion_suministro L1) 1)
(= (peticion_suministro L2) 2)
(= (peticion_suministro L3) 1)
(= (peticion_suministro L4) 2)
(= (peticion_suministro L5) 2)
(= (recursos_restantes) 3)
)
(:goal (or
    (forall (?l - lugar) (and (= (peticion_persona ?l) 0) (= (peticion_suministro ?l) 0)))
    (= (recursos_restantes) 0)
))
(:metric maximize (combustible_total)))
